language: ruby
rvm:
- ruby-head
- 2.1.0
- 2.0.0
- 1.9.3
- 1.9.2
matrix:
  allow_failures:
  - rvm: ruby-head
deploy:
  provider: rubygems
  api_key:
    secure: PLHZ+N2quWfUJgMR0Ckt/w51KW1GYruC9Ebo6hGs9rx1tLQqMSAkhRIj1YRzU/KacWqUEwCw8onHswBowzf2H3enWlYvyQ8jcLWuZCpATAukOHP5SnmUqV8EqIqD9A0cX1vemU/7Eg2HQ1aq3bnNbqhZWs2JeTw7NsguPjoWikI=
  gem: cucumber-formatters
  on:
    repo: benSlaughter/cucumber-formatters
    branch: master